### ISSUE TITLE
Missing argument --minwarnings

### ISSUE THREAD

**Issue by SteinHeselmans** [melexis/warnings-plugin#10]
Some users might want to use this plugin in order to assert how many warnings a certain plugin throws on some example input. Then we need to support for a minimal threshold of warnings...

Example in https://github.com/melexis/sphinx-traceability-extension/blob/master/tox.ini#L19 when one might to assert that this command throws at least x warnings...

**Comment by Letme** [comment]
I would say #7 would solve this...

**Comment by SteinHeselmans** [comment]
sure, just keep this one open in order to not forget to provide a minimal threshold?
