### ISSUE TITLE
Issue with license and pypi

### ISSUE THREAD

**Issue by SteinHeselmans** [melexis/warnings-plugin#12]
License is Apache2, while pypi still reports MIT.

In other packages, i see that pypi doesn't support Apache2 and travis ci logs give a message about that.

**Comment by SteinHeselmans** [comment]
example solution can be found in https://github.com/melexis/jira-juggler/commit/331c8e0466ae8fcb4046089fcc3628b45495bd6f

**Comment by Letme** [comment]
Em ok then apply that to this repo as well :smile:
