### ISSUE TITLE
Refactor to use more classes

### ISSUE THREAD

**Issue by SteinHeselmans** [melexis/warnings-plugin#19]
Suggestion to use more classes for the plugin

An abstract class with property for min/max/count/regex/...

A derived class for every parser we have (junit/doxy/sphinx) implementing the parsing per parser, this is easier to extend with more checkers.

The min and max can become part of the class so we'll have different min/max levels specific per parser...

Reporting could be a separate class, or we use Logger object...

**Comment by SteinHeselmans** [comment]
Also, provide an option to print the warnings the plugin finds to terminal (see https://github.com/melexis/warnings-plugin/pull/16#discussion_r123747201 for details)

**Comment by bavovanachte** [comment]
Could you make a first proposal using a class/inheritance diagram? I think that allows for easier discussions
