### ISSUE TITLE
JUnit part should be using some junit parser

### ISSUE THREAD

**Issue by SteinHeselmans** [melexis/warnings-plugin#20]
Example of such a parser: https://pypi.python.org/pypi/xunitparser

**Comment by SteinHeselmans** [comment]
also support for multiple xml files from command line, or a recursive folder argument would be nice. JUnit xml files never come alone :wink:  usually one per component/module...

**Comment by SteinHeselmans** [comment]
Investigated the use of a parser lib. We definitely need parsing from string as we will be implementing #3 shortly and i suppose we don't want to generate intermediate files that will be loaded again by a parser. So load from string is importatnt.

Summary of the modules we could use:

- xunitparser (https://pypi.python.org/pypi/xunitparser) is pretty mature (1.3.3), does not support reading from string, only from file. Contribution is by sending git patches to the maintainer... Tested functionality on python2: load from file works, on python3: does not seem to work at first glance.

- junitparser (https://pypi.python.org/pypi/junitparser/) is pretty young (0.1), but claims to be fun :wink:. Does support reading from string, but no python2. Not tried yet. Contribution is on github.

- others (xunitgen, xunitmerge, junit-xml) do not support loading xml out of the box (only generating and merging)

I'm more in for junitparser, because of 

- the fun part :wink: 
- github contributions
- supports load from string
- port to python2 is probably (?) not that hard so that could be our contribution

thoughts? @Letme @bavovanachte @bollenn

**Comment by bavovanachte** [comment]
Junitparser looks nice, indeed. Could you contact the maintainer, to see if he would accept python2 compatibility? Of course we can make an MR to make the current state py2 compatible, but it needs to remain supported in the future as well.

**Comment by bavovanachte** [comment]
Wrong button, sorry

**Comment by SteinHeselmans** [comment]
junitparser question can be tracked in https://github.com/gastlygem/junitparser/issues/2

**Comment by Letme** [comment]
I am ok with junitparser and making it python2 compatible. If we add a python2 unit test environment we can keep it supported in the future as well.
