### ISSUE TITLE
Plantuml not found

### ISSUE THREAD

**Issue by Letme** [melexis/warnings-plugin#45]
I guess we missed the warning inside the CI (there we go for not dogfooding) for Sphinx

```
WARNING: plantuml command 'plantuml' cannot be run
```

We install sphinxcontrib-plantuml, but dont install plantuml itself I would assume. Needs investigation.

**Comment by SteinHeselmans** [comment]
hmm indeed never checked that. We only need that to build design.rst as there is a class diagram in there.

More questions:

Does CI execute this build of docs? If yes, why doesn't it fail because of the missing plantuml?

Where do the artifacts end up?

**Comment by Letme** [comment]
Its a warning and sphinx returns 0 :smile:

One of the reasons we developed this plugin... CI does execute build of docs, but no idea where do artifacts end up.
