### ISSUE TITLE
Apply warnings plugin on Coverity Defects

### ISSUE THREAD

**Issue by Letme** [melexis/warnings-plugin#47]
We need another checker for increased Coverity Defects. Also in consideration we could use checker for cppcheck or any other static analysis tool.

**Comment by bollenn** [comment]
Any progress/planning on this?

**Comment by Letme** [comment]
I remembered why there is no progress on this. While it is possible to obtain items locally inside job (`cov-format-errors --dir idir --json-output-v2 idir/report/summary.json` ), it will not include information from Triage Store. That means we rather need to query the Coverity server to obtain the number of non-intentional, non-falsepositive defects. 

So proper solution to this is that Warnings Plugin would need to query the Coverity server to get Defects (https://github.com/melexis/sphinx-coverity-extension/blob/master/mlx/coverity_services.py#L282). I would suggest going this way as it will have a lot less false-positives than the alternative. It can be part of warnings plugin or as a separate tool... If you need infrastructure from warnings-plugin then you can make a new checker that uses/runs an API.

**Comment by SteinHeselmans** [comment]
I'm not sure if that is a good approach. It sounds like a big task for the script to contact coverity server (also think about config for url, user) in order to parse warnings. Warnings plugin is a simple regex/xml-based parser, contacting a server would not fit that simple plan?

**Comment by Letme** [comment]
As seen in #74 it does bring in a lot of dependencies and bloats what is now a simple plugin. However since there were some requests for this functionality and based that the framework is in place, I do not see it as a bad idea. With this example we can now query other servers for warnings/errors.

**Comment by bavovanachte** [comment]
Doesn't it make more sense to split the coverity part off into a separate plugin, and make that include the warnings plugin instead? I feel like this would open up the plugin to other ways of actively looking for inputs, which could become very hard to maintain.

**Comment by Letme** [comment]
OK, I did more digging for 1 in the MR #74 . as that seems more useful usecase for us.

We only want basically to check the changes between current branch and master in CI. This can be achieved with:

```
cov-run-desktop --exit1-if-defects true `git diff --name-only --ignore-submodules master`
```

If you want to eliminate some files I suggest pipe-ing `git diff` to `sed` for something like
```
sed '/src\/somepattern\|src\/someotherpattern\//!d'
```
Gets you list of all defects in that file (changes) in terminal and exits 1 if they exist.  So we can remove `exit1-if-defects` and just live happily with 0 as return value, but we need plugin to parse the output which looks like:

```
filename.c:90: CID 112675 (#2 of 2):
  Type: Coding standard violation (MISRA C-2012 Rule 10.4)
  Classification: Unclassified
  Severity: Unspecified
  Action: Undecided
  Owner: somebody
  First detected on 2017-07-27.
somefilename.c:90:
  1. misra_violation: Essential type of the left hand operand "counter" (unsigned) is not the same as that of the right operand "4U"(signed).
```

This above is the test case we in fact need to increment count of defects but only if classification is `Bug`, `Pending`, `Unclassified`. However there is some noise and below output should **NOT** be reported as defect (its just part of the defect). We only want where numbers **THIS** are equal after `CID NUM (#THIS of THIS):`

```
filename.c:88: CID 112675 (#1 of 2):
  Type: Coding standard violation (MISRA C-2012 Rule 10.4)
  Classification: Unclassified
  Severity: Unspecified
  Action: Undecided
  Owner: somebody
  First detected on 2017-07-27.
somefilename.c:88:
  1. misra_violation: Essential type of the left hand operand "counter" (unsigned) is not the same as that of the right operand "64U"(signed).
```

I think this is indeed more suitable solution for the plugin, but it brings in dependency on `cov-run-desktop` (which does the query of Coverity Server). In CI also `cov-run-desktop --setup` will be required (assuming there is `coverity.conf` in project root)

**Comment by Letme** [comment]
This got whole lot easier with `cov-run-desktop --text-output-style=oneline`

```
filename.c:88: CID 112675 (#1 of 2): Coding standard violation (MISRA C-2012 Rule 10.4): Unclassified, Unspecified, Undecided, owner is cmo, first detected on 2017-07-27.
somefile.c:88: 1. misra_violation: Essential type of the left hand operand "counter" (unsigned) is not the same as that of the right operand "64U"(signed).

filename.c:90: CID 112675 (#2 of 2): Coding standard violation (MISRA C-2012 Rule 10.4): Unclassified, Unspecified, Undecided, owner is cmo, first detected on 2017-07-27.
somefile.c:90: 1. misra_violation: Essential type of the left hand operand "counter" (unsigned) is not the same as that of the right operand "4U"(signed).
```
