### ISSUE TITLE
Some RST warnings are not recognized

### ISSUE THREAD

**Issue by SteinHeselmans** [melexis/warnings-plugin#8]
Example of warning not recognized:

```
/path/to/file.rst:None: WARNING: Traceability: cannot link to XXX, item is not defined
```

Rumours say it is because of a missing line number, and more rumours say that this regex would work

```
^(.+?:None): (DEBUG|INFO|WARNING|ERROR|SEVERE): (.+)\n?$
```

Warning is from mlx.traceability plugin, which could print a line number iso the None (see issue https://github.com/melexis/sphinx-traceability-extension/issues/2).

**Comment by bavovanachte** [comment]
Extending the existing regex to the following should do the trick:

```
^(.+?:(?:\d+|None)): (DEBUG|INFO|WARNING|ERROR|SEVERE): (.+)\n?$
```
